fix bugs

diff --git a/scripts/ddns-start b/scripts/ddns-start
--- a/scripts/ddns-start
+++ b/scripts/ddns-start
@@ -1,7 +1,10 @@
-#!/bin/sh -e
+#!/bin/sh 
 
 . $(dirname $0)/common/_log
 . $(dirname $0)/common/_notify
+. $(dirname $0)/common/_noConcurrency
+echo $$
+#noConcurrency
 
 DDNS_CONFIG_FILE="$HOME/.ddns_config/aliyun_config"
 accessKeyID=`grep "accessKeyId" $DDNS_CONFIG_FILE|sed 's/.*=\ //g'`
@@ -9,7 +12,8 @@ accessKeySecret=`grep "accessKeySecret" $DDNS_CONFIG_FILE|sed 's/.*=\ //g'`
 recordID='89863902'
 RR='ssh'
 IP=`ip addr show ppp0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1`
-CURRENT_RESOLVED_IP=`nslookup ssh.shikun.win 223.5.5.5|tail -n 2|grep Address|awk -F": " '{print $2}'`
+#CURRENT_RESOLVED_IP=`nslookup ssh.shikun.win 223.5.5.5|grep -A1 Name|grep Address|awk -F": " '{print $2}'`
+CURRENT_RESOLVED_IP=`nslookup ssh.shikun.win dns9.hichina.com|grep -A1 Name|grep Address|awk -F": " '{print $2}'`
 echo IP:$IP
 echo CURRENT_RESOLVED_IP:$CURRENT_RESOLVED_IP
 
@@ -19,6 +23,8 @@ then
         /sbin/ddns_custom_updated 0
 	exit 
 fi
+
+[ -z $CURRENT_RESOLVED_IP ] && log "dns resolved failed"  && exit 1
 
 log "ssh.shikun.win is updated, result: $(/mnt/sda1/MGMT/ddns/aliyun_ddns.py $IP $accessKeyID $accessKeySecret $recordID $RR)"
 send_notify "DDNS Updated" "ssh.shikun.win -> ${CURRENT_RESOLVED_IP}"
